### ISSUE TITLE
目前脚本只能识别有一个任务点的章节

### ISSUE THREAD

**Issue by Itsusinn** [LuDreamst/xuexitong_auto_play#1]
目前脚本只能识别有一个任务点的章节，想必作者也没考虑多个任务点的鼠标滑轮模拟控制
> 注: 此issue为repo作者到我家里做客时,抢过我的键盘发出的

**Comment by LuDreamst** [comment]
已修复只识别一个任务点的问题，并添加多个任务点以及不同类型任务点的识别处理能力

**Comment by LuDreamst** [comment]
closed
